dataset_pattern: /data/t3home000/snarayan/papu/data_v2/TTBar_*npz 
output: /data/t3home000/snarayan/papu/expts/3/16_6_20_8x8_mse/ 
n_epochs: 100

embedding_size: 128
hidden_size: 128
intermediate_size: 128
feature_size: 12 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 6
label_size: 1
attention_band: 20

batch_size: 64 
grad_acc: 8
mask_charged: True 
lr: 0.001
lr_decay: 0.9
lr_policy: 'exp'
num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /home/snarayan/public_html/figs/papu/scan3/128_6_20_16_mse/
pt_weight: True
#beta: True
