dataset_pattern: /data/t3home000/snarayan/papu/data_v1/WJets_*npz 
output: /data/t3home000/snarayan/papu/expts/2/16_4_20_48_mse/ 
n_epochs: 100

embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 4
label_size: 1
attention_band: 20

batch_size: 48 
mask_charged: True 
lr: 0.0005
lr_decay: 0.99
num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /home/snarayan/public_html/figs/papu/scan2/16_4_20_48_mse/
pt_weight: True
#beta: True
