dataset_pattern: [/local/grapple/hinv_pu_fixedjets/2020_04_23_11_39_02/*npz]
#dataset_pattern: [/local/grapple/hinv_pu/2020_04_20_22_40_44/*npz]
weights: /local/grapple/all_pu_dr/0.4/2020_04_22_10_05_04/model_weights_epoch24.pt 
mask_charged: True

embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 4
label_size: 2
met_poly_degree: 4
met_layers: 2

batch_size: 8 
num_max_files: 4
num_max_particles: 2000
plot: /home/snarayan/public_html/figs/grapple/all_pu_dr/0.4/hinv_jets/
pt_weight: True
dr_adj: 0.4
