train_dataset_pattern: /local/grapple/qcd/2020_04_17_13_14_05/*npz 
test_dataset_pattern: /local/grapple/qcd/2020_04_17_13_14_05/*npz 
output: /local/grapple/qcd/v4/
n_epochs: 50
embedding_size: 32
hidden_size: 32
intermediate_size: 32
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 8
num_encoders: 4 
batch_size: 256 
mask_charged: False 
lr: 0.0002
lr_decay: 0.99 
dr_adj: 0.25
#num_max_files: 20
#min_met: 50
plot: /home/snarayan/public_html/figs/grapple/qcd_0/
