dataset_pattern: /local/grapple/qcd/2020_04_17_13_14_05/*npz 
output: /local/grapple/qcd_pu/v0/
n_epochs: 50
embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 8
num_encoders: 8
batch_size: 16
#mask_charged: True 
lr: 0.0002
lr_decay: 0.99 
label_size: 2
#dr_adj: 0.25
#num_max_files: 5 
num_max_particles: 1000
#min_met: 50
plot: /home/snarayan/public_html/figs/grapple/qcd_0/
#pt_weight: True
