dataset_pattern: /local/grapple/wjets_pu/2020_04_18_17_42_29/*npz 
output: /local/grapple/wjets_pu/v0/
n_epochs: 50
embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 8
num_encoders: 4
batch_size: 8 
mask_charged: True 
lr: 0.0002
lr_decay: 0.9
label_size: 2
#dr_adj: 0.25
num_max_files: 1 
num_max_particles: 250
#min_met: 50
plot: /home/snarayan/public_html/figs/grapple/wjets_pu_1/
pt_weight: True
dr_adj: 0.2
