dataset_pattern: /local/grapple/hinv_pu/2020_04_19_23_23_17//*npz 
output: /local/grapple/hinv_pu/v0/
n_epochs: 10
embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 1
num_encoders: 4
batch_size: 4 
mask_charged: True 
lr: 0.0002
lr_decay: 0.98
label_size: 2
#dr_adj: 0.25
#num_max_files: 100 
num_max_particles: 2000
#min_met: 50
plot: /home/snarayan/public_html/figs/grapple/hinv_pu_0/
pt_weight: True
#dr_adj: 0.4
met_poly_degree: 4
met_layers: 2
