dataset_pattern: /local/grapple/data/v0/2019_12_18_20_49_41/data_*.npz
output: /local/grapple/results/v2/
n_epochs: 50
embedding_size: 64 
hidden_size: 64
intermediate_size: 64
feature_size: 5
label_size: 2
num_hidden_layers: 2
num_attention_heads: 4
num_encoders: 2
batch_size: 8
mask_charged: True
lr: 0.001
lr_decay: 0.1
