dataset_pattern: /local/grapple/data/test/output/2020_01_15_22_33_08/*npz 
output: /local/grapple/results/test/
n_epochs: 50
embedding_size: 64 
hidden_size: 64
intermediate_size: 64
feature_size: 6
label_size: 2
num_hidden_layers: 2
num_attention_heads: 4
num_encoders: 2
batch_size: 8
mask_charged: True
lr: 0.001
lr_decay: 0.1
plot: /home/snarayan/public_html/figs/grapple/test_big/
