dataset_pattern: /local/grapple/wjets_presel/2020_04_10_19_26_14/*npz 
output: /local/grapple/wjets/v2/
n_epochs: 50
embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 2 
num_attention_heads: 4
num_encoders: 2 
batch_size: 12 
mask_charged: False 
lr: 0.001
lr_decay: 0.8
#num_max_files: 2
#min_met: 50
plot: /home/snarayan/public_html/figs/grapple/wmn_3/
