dataset_pattern: /data/t3home000/bmaier/data_preconvert_cluster30/WJets_*npz 
output: /data/t3home000/snarayan/papu/expts/scan_0/v0_30/
n_epochs: 50

embedding_size: 16
hidden_size: 16
intermediate_size: 16
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 4
label_size: 1
attention_band: 35

batch_size: 32 
mask_charged: True 
lr: 0.0005
lr_decay: 0.98
num_max_files: 10
num_max_particles: 7000
#min_met: 50
plot: /home/snarayan/public_html/figs/papu/v0_30/
pt_weight: True 
