dataset_pattern: /data/t3home000/snarayan/papu/data_v2/TTBar_*npz 
output: /data/t3home000/snarayan/papu/expts/3/16_4_20_32_mse/ 
n_epochs: 100

embedding_size: 24
hidden_size: 24
intermediate_size: 24
feature_size: 12 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 6
label_size: 1
attention_band: 20

batch_size: 16 
mask_charged: True 
lr: 0.001
lr_decay: 0.66
lr_policy: 'cyclic'
#num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /home/snarayan/public_html/figs/papu/scan3/24_6_20_16_mse_cyclic/
pt_weight: True
#beta: True
