dataset_pattern: /data/t3home000/bmaier/data_preconvert_9000/WJets_*npz 
output: /data/t3home000/snarayan/papu/expts/1/32_4_20_32/ 
n_epochs: 50

embedding_size: 32
hidden_size: 32
intermediate_size: 32
feature_size: 6 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 4
label_size: 1
attention_band: 20

batch_size: 32
mask_charged: True 
lr: 0.0005
lr_decay: 0.99
num_max_files: 20
num_max_particles: 9000
#min_met: 50
plot: /home/snarayan/public_html/figs/papu/scan1/32_4_20_32/
pt_weight: True